name: Deploy Laravel Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.2'


      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Install Dependencies
#        run: composer update --ignore-platform-reqs

      - name: Copy .env file
        run: cp .env.example .env

#      - name: Clear Config Cache
#        run: php artisan config:clear

      - name: Directory Permissions
        run: chmod -R 775 storage

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
